### ISSUE TITLE
No stream on RX1 and RX2 or both

### ISSUE THREAD

**Issue by dl5rdq** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#142]
EESDR3 when switching on is no stream on RX1 or RX2 or both, only after switching on again then stream on RX1 ...RX2 is then on TX ! EESDR3 when switching on no tune and no TX possible, is not to dial. Only after renewed or repeated switching on ok !

If SDC is off and I start eesd3 , then everything is ok! if then eesdr3 is running and I start SDC , then I have the error ! If I start SDC first and then eesdr3 , then everything is ok too. !

**Comment by hb9bun** [comment]
Testing it showed that it is connected to the use of SDC Rig Emulator. This happens if RIG Emulator is on and no active CAT client is connected. With e.g. N1MM+ connected to the CAT ports everything works fine, if the CAT ports are open and RIG emulator is on ESDR shows this strange behaviour at startup. Somehow TCI is getting wrong/invalid input through SDC from the not connected CAT ports.

**Comment by ExpertSDR3** [comment]
Most likely, this is due to an error in the synchronization between TSI and CAT. We are currently working on our own utility for synchronization CAT<->TCI, which will correctly perform synchronization.
