### ISSUE TITLE
ESDR3: PA setting "save by band"

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#185]
ESDR3 V 0.11.0 alpha Build: 28122021
SunSDR2DX
Win 10

When putting in Settings - PA settings - "Save by band" to on, the PA button just disappears. So the PA PTT can not be enabled/disabled by band as I would expect with this setting. What is the purpose of this option then? 
73, Peter

**Comment by N8SDR007** [comment]
Two-Fold

If you have AMP and Antennas that would work on all bands then having the PA button to enable disable is handy

For me that doesn't work because I don't want the AMP to be able to KEY say on 30/60/or 160 since I do not have resonate antennas for them So I don't check those bands in the BM. but when I switch to a band that would allow the AMP to function into a good antenna then the Keyline is triggered, and I am good to go if I engage the AMP

**Comment by ExpertSDR3** [comment]
If you switch on the PA by Band, then the BandManager will show a jackdaw for each band
