### ISSUE TITLE
Very slow reaction fo SunSDR2 to ESDR3

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#244]
ESDR3 0.11.0 alpha Build 30122021
Win 10
SunSDR2 DX

Just once in a month I suddenly had the issue, that starting ESDR3 led frist to a white screen, only after about 10-12 sec. ESDR3 started. And then the SunSDR2 DX only reacted after about the same time to buttons. Often the Bandscope was stopping for a couple of seconds. 

Stopping ESDR3, restarting, reinstalling it did not help. Restarting the PC did twice not help. Also taking firewall off and on again had no effect. Something slowed down the communication between ESDR3 and the SunSDR2 DX. After 2 restarts and about 1 minute of operating and playing with JTDX and ESDR3 (changing bands) - suddenly the SunSDR2 DX reacted again without delay. 

ESDR2 worked just normal with the same SunSDR2 DX when testing in between. 

Since then it did not happen again. I cannot reproduce the issues. Just reporting it in case someone else sees similar effects.

**Comment by danweecc** [comment]
Sounds like your network is having some issues. The above symptoms sound like inconsistent network performance.

**Comment by hb9bun** [comment]
Agree, interesting that it just affected the communication between ESDR3 and the SunSDR2 DX. It did not happen before and not anymore.

**Comment by danweecc** [comment]
Communications between the machine EESDR3 is running on, and the SunSDR2DX needs to have a fairly low latency (I heard <5ms but a bit higher in practice still works). Once the latency goes above that for any reason, you will start to see dropped packets which can result in loss of audio, as well as delay in commands. This can happen, especially, if any of the links involves Wi-Fi connections. This isn't really a bug, as such, but just a system requirement. If you are using Wi-Fi, switch to wired LAN and the problems should go away. If you're using wired LAN and still seeing such problems, you might have some more serious network issues.

Additionally, it might be due to the EESDR3 host machine being overloaded. If this is a Windows machine, there are some tweaks you can do to prioritize network communications that could reduce lag. These involve registry modifications.

**Comment by hb9bun** [comment]
Thank you. I am using a wired connection. The network is very stable and performing well. I did check also network load and pinged the connection. No latency issue. 
Also when switching to ESDR2 the connection to the SunSDR2 had no issues at all. It was just ESDR3 to SunSDR2 DX that was concerned. That was the reason to post it. 
The issue only happened once, with ESDR3 and SunSDR2 DX having been connected for hours. 
Really strange. Also that for a longer period the response time were about 10s - and remaining like that. Like waiting for a timeout and then replying. **And even restarting the he EESDR3 host machine did not help.** 

With previous versions of EESDR3 alpha I had effects like after having it run over night the bandscope display was sometimes freezing for 2 seconds or so. But after a restart it worked normally. This effect here was really strange. Thanks for the hints. I am quite sure my network is working fine - especially as switching to ESDR2 with the same SunSDR2 DX was possible without issues. Coming back the slow start was there again. 

I hope it will never happen again.

**Comment by danweecc** [comment]
Is it possible that it is something to do with the Windows installation? Maybe try this on a different machine just to see if there might be some interaction with the OS. It is good that EESDR2 works though. I run my radio 24/7 and have not seen freezing although occasionally the connection will drop (VPN over Internet) due to latency issues. Don't if this will be relevant:-

https://ttcshelbyville.wordpress.com/2017/10/14/network-throttling-index/?fbclid=IwAR10R0-WEUsGnWEfRFuy0pubmDDDWjRFT2CbSkcVSsCYCCM12yEpnFANHeo

**Comment by hb9bun** [comment]
Thinking about it: It was probably more something in a queue that had to be cleared. I am using many different components via TCI, PA, SDC, RC version of JTDX. 
As it was just ESDR3 that had these delays with SunSDR2 and it has gone away during operation when manipulating actually in JTDX, maybe an issue with an improper TCI command (for a while regional settings with not expected characters caused ESDR3 to crash).  
Thanks for your hints!

**Comment by hb9bun** [comment]
It only happened once and I cannot reproduce it and yes, my machine also runs 24/7 decoding FT8. I only report it as sometimes I then get feedback that the same happens in other configs. So if it should happen again, I will for sure try to test systematically.

**Comment by danweecc** [comment]
Ah ok, now that makes sense. I have noticed that when EESDR3 is serving multiple TCI clients on the same machine, it sometimes chokes. I ended up running SDC on a different machine and that seems to be okay for now. You may want to consider off loading the TCI clients to other machines on the same network. I currently have SDC running on a separate Linux machine, and a bit of hardware that controls my SPE amplifier. Both of them, along with JTDX talks to EESDR3. Sometimes I run Log4OM as well. The main culprit appears to be SDC.

**Comment by hb9bun** [comment]
Actually I do not see a lot of load when SDC is running as well. I had as mentioned in the past effects on EESDR3 with wrongly formated TCI commands arriving. They stopped EESDR or made it crashing. I am using the PA connected via TCI, JTDX, RadioSync, SDC connecting the log program via Commander - all via TCI. I do not think that under normal conditions this does stress my high gaming PC with a powerful NVIDIA graphics card a lot.

**Comment by rkayakr** [comment]
I always see the same problem of extreme slowness. If I try to adjust a slider the screen freezes for several seconds and then the slider is not where intended. ExpetSDR3 is not usable for me.

ExpertSDR2 runs well, as does all of the software for my similar Hermes Lite 2 SDR transceiver which also Ethernet connects. The computer is not heavily loaded, it's just loafing along.
 
Set up:
SunSDR DX directly cabled to PC, Wifi out to the universe
Windows 10
Processor Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 1.99 GHz
Installed RAM 16.0 GB (15.9 GB usable)
Nvidia GeForce MX150 graphics card

    Bob   KD8CGH
