### ISSUE TITLE
Software going off frequency

### ISSUE THREAD

**Issue by Kb2uka** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#246]
V3 0.11.0 latest release
Mac version
Sunsdr2dx

2 weeks ago, I started getting reports that I was slightly off frequency. The vfo stays on freq and rit and xit are not engaged. 

I have no way to tell I'm off freq unless someone tells me. 

I shut the software down and relaunch and I am back on frequency.

This only started happening 2 weeks ago, software has been installed over a month.

**Comment by danweecc** [comment]
What modes were you working? CW, SSB or DIGI?

**Comment by Kb2uka** [comment]
Just SSB.

**Comment by JamesWSchafer** [comment]
VK4CS I am having the same problem. I only know when I am told that I am off frequency, normally 1kh high

**Comment by danweecc** [comment]
Are you using EESDR3 in conjunction with some software that is controlling the frequency via TCI? Did you check if XIT was active?

**Comment by JamesWSchafer** [comment]
I was using MMSSTV and JTDX . XIT and RIT are not active. I am using windows 10 and EESDR3 build 30122021. JTDX can be used to control the frequency, it was on the same freq that EESDR3 was set on to receive so I don't believe it was an issue. Stations that I was QSOing with were seeing my signal 1khz above what it should have been.

**Comment by Kb2uka** [comment]
> Are you using EESDR3 in conjunction with some software that is controlling the frequency via TCI? Did you check if XIT was active?

I use max logger but this is happening when max logger is NOT active. Thanks. 

Doug

**Comment by Kb2uka** [comment]
> I was using MMSSTV and JTDX . XIT and RIT are not active. I am using windows 10 and EESDR3 build 30122021. JTDX can be used to control the frequency, it was on the same freq that EESDR3 was set on to receive so I don't believe it was an issue. Stations that I was QSOing with were seeing my signal 1khz above what it should have been.  

So strange, I'm about 1khz low.

**Comment by danweecc** [comment]
I think part of the problem might be EESDR3 having some bugs in some of the TCI implementation. I've been corresponding with the author of JTDX and noticing some of such problems but the core issue here were some bugs in the EESDR3 TCI implementation with respect to the VFOB. I think you won't have such problems if you use "Fake It" at the moment. EESDR2 also should not see this problem. It specifically has to do with how VFOB is initialized. If this should happen, try changing bands from JTDX and then back to the band in question. I believe this will be fixed in the next version of EESDR3.

**Comment by ExpertSDR3** [comment]
There were indeed errors in the management of VFOB from TCI, they were fixed in version 0.12, but work on version 0.12 is still ongoing.
