### ISSUE TITLE
expert sdr3 version .013.0 build 02092022 shutting down after selecting radio

### ISSUE THREAD

**Issue by VA3WU** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#409]
I have an HP laptop envy 360 I7 1165g7 intel IRIS xe graphics. build 08072022 starts and runs just fine. but build 02092022 starts the device manager fine when selecting a radio it brings up the radio screen and then it shuts down leaving the device manager running. i have tried different graphics setting but nothing works. just going back to the old version will allow me to run the radios on this laptop. the new version does work fine on all my other computers.

this happens on both my sunsdr 2 pro's or my sunsdr 2 dx

https://user-images.githubusercontent.com/100288084/188342280-1d5b7915-9a4e-48a4-91fb-44956d317367.mp4

**Comment by Sergey-R5AU** [comment]
Hi , proplem are with the scale factor on the screen of SDRapplication, probably you have selected other scale factor instead of 100% with previous Alfa version,
Heare are 2 ways out:
- for novice users ( )) )  just delete folder Expert Electronics in folder c:/users/... before installing new Alfa
- manage some Json files (change scale factor in editor) in folder c:/users/...expert electronics...related to ESDR3
