### ISSUE TITLE
right click on the NR button does not produce anything 0.13.0 alpha 02092022 firmware 79.8 Sunsdr2 Pro 

### ISSUE THREAD

**Issue by f6ctt** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#415]
A right click on the NR button does not produce anything on my Sunsdr2 Pro 02092022 0.13.0 alpha firmware 79.8

**Comment by VK6NX** [comment]
Does (tested on mac, linux, win; DX)

Produces Popup window with "Quality: 43 (default)". When default is changed - right click returns updated value to default. 

Check your settings. If still not working, supply video and common parameters.

**Comment by jmkr25** [comment]
F1DJY. I also see the same problem on NR with Sunsdr2Pro. Right click on NR does not display anything in 0.13.0 alpha 02092022 firmware 79.8

**Comment by VK6NX** [comment]
Well... Then you better do something. Do not really know what is should be. Instrusctions read, may be? Anything else?

Because it is working under Mac, Win and Linux on my DX and SS2. Proof: https://mega.nz/file/mNwgTazS#UhFdoNpXJH69-fodIHDbiWI47nmtd_s8swCwwci7-mA

(did video for Mac and DX only, because I am lazy. But I can proof it for all I have said before).

And, BTW, Learn how to fill github reports. Instructions are at first page.

**Comment by jmkr25** [comment]
Good! I don't question your word, but you do! The problem is very real and permanent.
Sunsdr2Pro EED02111800462, W11 21H2, HP Z2 I7 8700K, 16Go Ram, NVidia quadro K1200, 2 Display 4K 27 inch, ExpertSdr3 0.13 alpha 01091022, firmware 79.8, API Vulkan. I left clicked on NR, but the right click did nothing...and I can't show it on screenshot. 73
<img width="1397" alt="Capture d’écran 2022-09-10 165840" src="https://user-images.githubusercontent.com/16072964/189489482-20aaad38-43fa-41e6-adba-dab04a4c6cb2.png">

**Comment by VK6NX** [comment]
And your previous alpha version was?
And you did delete settings of previous alpha before installing 02022022?

**Comment by jmkr25** [comment]
So, I just removed Appdata ExpertSdr3 and reinstalled version 02/09. No luck, it didn't change anything at all. We will have to look elsewhere.

**Comment by jmkr25** [comment]
On the other hand, no problem on colibrinano
<img width="890" alt="Capture d’écran 2022-09-10 213542" src="https://user-images.githubusercontent.com/16072964/189499213-30c6caee-b0ba-4b46-8455-ac5a58cd2243.png">

**Comment by VK6NX** [comment]
How about other right clicks - NB, APF, ANF, ANC - are the right clicks working?

Try to re-image Firmware: load any of previos alpha, downgrade the Firmware; then load 02092022 and update Firmware (delete settings before first start of 02092022 launcher).

**Comment by VK6NX** [comment]
Also (and in relation to your #421) - test everything (what is not working) with direct ether cable connection, not on LAN.

**Comment by jmkr25** [comment]
NB, APF, ANF, ANC - right clicks is working.
It is the same firmware for Nano and Sun!!
Connection between Sun and PC is always direct 
**_The debate is closed._**

**Comment by VK6NX** [comment]
Debate? LOL.
No worries. No more help will be provided from my side for this and your future cases.

(Still working on all mine devices, as well as on (at least) 3 PROs which I know.)

**Comment by jmkr25** [comment]
Usually the EESDR **forum is the place for mutual assistance**, and **GitHub the place where we report observed bugs** and comments on these bugs.

**Comment by ExpertSDR3** [comment]
Fixed
