### ISSUE TITLE
AAT-100 ATU not achieving optimal match

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#478]
EESDR3 0.13.0 alpha build 25102022
SunSDR2DX
Windows  10 and 11 64-bit
AAT-100 version 1, revision 1

When using the AAT-100, the TUNE button initiates the tuning process but does not seem to achieve the best match.  For example, my antenna has a natural SWR of 1:1.6 on 20m (as displayed in EESDR3 with ATU off). After tuning, I might only be seeing 1:1.4. However, if I directly edit the settings file for that particular cell, I can manually get a 1:1.0 match. Similarly, with EESDR2, I also seem to be getting a better match. Please look at the tuning algorithm to see that it is in fact working optimally.

**Comment by VK6NX** [comment]
FYI: "manual 1:1 match" is not equal to "optimal" ATU match for 95% of tuning scenarios.

There are many influencing parameters, starting from antenna actual construction type, config, parameters and location and ending by cable length and parameters (because AAT-100 is local).

Also ESDR SWR meter is not the scientific instrument and cannot be used to judge "optimal" in context of this case. The specific antenna analyzers (like RigExpert AA-600 or alternatives) has to be used for such measurements.
