### ISSUE TITLE
CW  are terrible  verr 1.0.0 Beta

### ISSUE THREAD

**Issue by SM4IVE** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#486]
Cw are terrible if you move the wpm slider it goes crazzy its very difficult to transmit good cw   the doots are to fast comparerd to dash
something is really wako.

**Comment by SM4IVE** [comment]
trcv MB1 Prime   Win10 pro
Manipulator conected to key in  
TCI macro did behave the same
breakin or PTT  same behavior
Clicking on cw monitor in headphones
seems restart sw have some impact on behavior it got better

**Comment by VK6NX** [comment]
First - you video has no sound. Could you, please, check.

Second - the CW artifacts (if present) might also be a result of conflicting settings, specifically if you did install beta over one of previous alphas. But - because it is MB1 (special case) - I would say, consult with EE support via email how to reset the settings on your device.

**Comment by SM4IVE** [comment]
I did a new install and it seems the problem are gone for the moment
