### ISSUE TITLE
"Lost Connection" при подключении к N1MM+ через RadioSync 

### ISSUE THREAD

**Issue by UD2F** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#513]
Трансивер SunSDR2
ExpertSDR3 beta 1.0.1 + com0com + RadioSync + N1MM+
Windows 10 HOME

В данной связке, при попытке работать макросами из программы N1MM+ после передачи нескольких телеграфных макросов трансивер терял связь с программой (выскакивала табличка "Lost Connection..."), пропадал звук в наушниках и трансивер после его включения вновь переставал реагировать на что либо. Для продолжения работы приходилось перегружать все программы. Все повторялось циклично. Было установлено, что при выключении кнопки Break In все начало работать в нормальном режиме. Включение функции Break In приводило сразу же опять к  потере соединения трансивера с программой ESDR3. 
Было протестировано на 2-х разных компьютерах, со свеже установленой Виндовс 10. Тестировалась также версия ESDR3 альфа 0.13.0 от 08072022 и отдельная версия RadioSync 1.0 - был получен точно такой же результат. 
Данный баг подтвержден еще двумя коллегами.
Без включения кнопки Break In нет возможности без нажатия на педаль оперативно в случае необходимости передать что либо с манипулятора, подключенного к  трансиверу.

**Comment by HA1AH** [comment]
Yes, that's it. Thank you!

**Comment by HA1AH** [comment]
As discussed with Roman, I copy here my settings, as this bug still occurs on my computer with SunSDR2DX device.

What I now did:
-I uninstalled ExpertSDR3
-I removed the folders "ExpertSDR3" and "ExpertSDR3 Firmware" under C:\Users\fin\AppData\Local\Expert Electronics
-I removed the remaining "ExpertSDR3" folder under C:\Program Files\ExpertElectronics

-Then I installed the software with ExpertSDR3_x64_1.0.4_beta_setup.exe and choose the "Repair" option for the "Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.32.31332"
-Restarted the computer

-I configured my E-Coder:
![ecoder_settings](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/121314489/9ae22567-3ba3-4e16-9753-fa510e2f93fb)


I configured ExpertSDR3 to start RadioSync automatically:
![automatic_startup](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/121314489/22f030d6-64c1-4e8f-90e8-3a951ddbdbcd)




I have the following setup in RadioSync for TX1 and TX2:

![tx1](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/121314489/8805e258-a0bd-4e06-bf45-79b79a1eb6e2)

![tx2](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/121314489/5627bece-59bb-4039-a081-fcbb56b12493)

I have the following SO2R setup in N1MM:
![n1mm1](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/121314489/48957e73-fe07-4a48-b469-278951737933)

![n1mm2](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/121314489/73576ef6-46eb-47db-88e7-a049c2b596a6)

![n1mm33](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/121314489/4b9eb63a-5bc2-4829-9ade-27c435532e9e)


Between the virtual com3-com4 and com7-com10 port pairs I use com0com virtual serial cables.

Now I don't use SDC.

I activate in EESDR3 now only TX1. (However, in real contests I use boh TX1 and TX2.)

I send 15 times CQ from N1MM. Everything is OK.

I switch "Break In" on:
After 3 CQ Message the error occurs:

![error](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/121314489/58cc87f2-af67-4a71-8afa-470a7faf145c)


I don't use any extra antivirus software. Just the default Windows Defender is running.

Is there any log file, what I could send?
If you want you can access my computer through TeamViewer or something like that.

The firmware version:
![firmware](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/121314489/b89f33d0-ccb1-43a8-b787-f199abc4b207)


I tried to change the baude rate, the usage of DTR and RTS pins and some other options but nothing helped.

So currently I can only use my el-key paddle if I go to TX mode by pressing the foot switch.


73:
Tibor
HA1AH/HG5E

**Comment by HA1AH** [comment]
And here is the video demonstrating the bug:
https://www.youtube.com/watch?v=kqFEmQt-enM

**Comment by HA1AH** [comment]
I'VE FOUND IT!
If the PTT Delay is below 50ms in N1MM setup, then the error immediately occurs.
At 50ms it occurs seldom.
At 80ms it doesn't occur any more.

So with configuration it can be fine tuned, however the bug itself still exists.
ExpertSDR3 shouldn't loose the connection with the SunSDR2DX device, if some settings have too low value in N1MM!

UPDATE: I tested it in real contests. If I want to have it stable, I have to set the PTT delay to higher value. Then no crash, sofar OK. BUT this also means that here is a relative long silence at the beginning of the CW message. And this is not adequate, I try to explain, why: my TU message after a QSO completion is really just "TU". If I know there were multiple calling stations, I send only "TU". But if only a single station called me, then I want to send "TU HA1AH" after a QSO. Therefore, I press F3 for TU message and press F4 immediately for sending my callsign. And that is the problem: there is a relative long silent space between TU and HA1AH, which can be misinterpreted by caller stations: they call me right after TU, while I'm still sending my callsign.

So, please fix this issue, so that ExpertSDR doesn't loose the connection to the device, even if the PTT delay is set to 10 milliseconds.
