### ISSUE TITLE
ExpertSDR2 no run

### ISSUE THREAD

**Issue by EA5DF** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#54]
When I run  ESDR2 V3 have this problem, appear a window with this:
Cannot find the entry point for the CreateDXGIFactory2 procedure in the dynamic link library dxgi.dll

![Captura de pantalla 2021-11-19 19 10 52](https://user-images.githubusercontent.com/94709129/142671238-9b2c92f6-74fc-4c9f-b343-0815c692fc40.png)

**Comment by ExpertSDR3** [comment]
We have received several such messages, this is due to the transition to a new version of the Qt framework. There is the same version of ExpertSDR 3 built on the previous version, which runs on PCs on which such a window appears.

You can download it from [here](https://drive.google.com/file/d/1IgLcBNldLhG-ftwbIAGX2qkyDF94lq96/view?usp=sharing)
