### ISSUE TITLE
TCI version numbering error

### ISSUE THREAD

**Issue by OK2WY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#659]
The version number in TCI protocol is FLOAT, it means, that 1.10 < 1.9.  After 1.9 should be version 2.0 instead of wrong 1.10.
It affected third party applications such as SDC (no modulation with RTTY modem), JTDX (no modulation, random freezing of EESDR)

**Comment by ExpertSDR3** [comment]
This is not a bug, the minor version increases when new commands are added, without breaking backward compatibility. 
But as it turned out, a lot of software incorrectly extracts the minor version, so in version ESDR3 1.0.7, the TCI 2.0 version will be renamed for compatibility with third-party software.

**Comment by OK2WY** [comment]
If you defined the protocol version number as FLOAT, you should expect that almost everyone of the third party apps programmers use the simple > or < conditions for the version detection. Could you please do it ASAP? Most of digi modes apps using TCI  are affected by this issue what prevent their users from updating EESDR to newest version.
