### ISSUE TITLE
dBm Scale changes with Rx audio settings

### ISSUE THREAD

**Issue by W3FRG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#83]
The Rx audio is very, very loud at turn on when set and its lowest setting on the slider, -56dB.
I set -30dB and then -50 db in the B.M table for Rx settings to reduce the volume. The audio volume does change but the vertical scale on the Spectrum display also changes by the amount selected.
See attached pictures.

![-30dB on B M Rx Audio](https://user-images.githubusercontent.com/94790391/142764101-1bd80ca2-28be-40af-803c-47c4e789196e.jpg)
![-50dB on B M Rx Audio](https://user-images.githubusercontent.com/94790391/142764102-24b38f83-8870-4a3d-8533-f6f171ec2cd7.jpg)

**Comment by ExpertSDR3** [comment]
RX GAIN is needed to adjust the radio signal level when using external filters or preamps, because they can weaken or amplify the input radio signal, RX GAIN is used to compensate for the signal level. If you have an antenna connected directly to the transceiver then the RX GAIN should be equal to 0 dB.
